baseURL = 'https://www.daniel-bethell.dev/'
languageCode = 'en'
title = "Daniel's Blog"
theme = "PaperMod"
paginate = 10

[params.homeInfoParams]
Title = "Hello Stranger"
Content = "Hi, this is Daniel! Welcome to my blog, this is where you will find all of my tutorials and other generic posts regarding AI and ML."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/dan_bethell"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/daniel-bethell/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/team-daniel"

[[params.socialIcons]]
name = "orcid"
url = "https://orcid.org/0000-0002-0685-5312"

[outputs]
home = [ "HTML", "RSS", "JSON" ]


[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  env = "production"

[params.assets]
  favicon = "/static/favicon.ico"
  favicon16x16 = "/static/favicon-16x16.png"
  favicon32x32 = "/static/favicon-32x32.png"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'Posts'
  url = '/posts/'
  weight = 10

[[menu.main]]
  identifier = 'categories'
  name = 'Categories'
  url = '/categories/'
  weight = 20

[[menu.main]]
  identifier = 'tags'
  name = 'Tags'
  url = '/tags/'
  weight = 30

[[menu.main]]
  identifier = 'faq'
  name = 'FAQ'
  url = '/faq/'
  weight = 40

  [[menu.main]]
  identifier = 'search'
  name = 'Search'
  url = '/search/'
  weight = 50
